config/routes.rb
Rails.application.routes.draw do
  get 'schools/create'

  get 'schools/new'

  get 'schools/destroy'

  get 'schools/index'

  get 'schools/update'

  get 'schools/show'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'comments/create'

  devise_for :users
  resources :schools
  resources :courses do 
    resources :comments, only: [:create]
  end

   root 'courses#index'

end

app/models/school.rb
class School < ActiveRecord::Base
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_school, only: [:update, :destroy]

  def create
    @school = School.new(school_params)
    

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @school = School.new
  end

  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_index , notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index

  end

  def edit 
    @school = School.find(params[:id])
  end 

  def show
    @school = School.find(params[:id])
    @schools = School.all
  end

  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'school was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :email, :rut_school, :company_name, :bank_account)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rut_school %><br>
    <%= f.number_field :rut_school %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :bank_account %><br>
    <%= f.number_field :bank_account %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/_schools.html.erb
<% @schools.each do |school| %>
    <tr>
        <td><%= school.name %></td>
        <td><%= school.rut_school %></td>
        <td><%= school.email %></td>
        <td><%= school.company_name %></td>
        <td><%= school.bank_account %></td>
        <td><%= link_to 'Edit', schools_edith_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>

app/views/schools/create.html.erb
<h1>Schools#create</h1>
<p>Find me in app/views/schools/create.html.erb</p>

app/views/schools/destroy.html.erb
<h1>Schools#destroy</h1>
<p>Find me in app/views/schools/destroy.html.erb</p>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>
<%= link_to 'Back to Courses', courses_path %>
<%= link_to 'Show', school_path %> |

app/views/schools/index.html.erb
<%= link_to 'New  School', schools_new_path %>

<form>
  <input name="query" id="q" <%= @q %> >
  <button type="submit" placeholder="Search here your course"> Search </button>
</form>

<h1>Listing Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rut School</th>
      <th>Email</th>
      <th>Company Name</th>
      <th>Bank Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='schools'>
  
    <%= render partial: "schools/schools", collection: @schools %>
      
  </tbody>

</table>

<br>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>
<%= link_to 'Back to Courses', courses_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Rut_school:</strong>
  <%= @school.rut_school %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @school.company_name %>
</p>

<p>
  <strong>Bank Account:</strong>
  <%= @school.bank_account%>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_index_path  %>

app/views/schools/update.html.erb
<h1>Schools#update</h1>
<p>Find me in app/views/schools/update.html.erb</p>